### ISSUE TITLE
Bug: Tips not being registered properly.

### ISSUE THREAD

**Issue by pokkst** [pokkst/tipbitcoin.cash#1]
This one has been stressing me out since it first started showing up.

# What happens?

When someone generates an invoice and the user sends to the address displayed, the tip sometimes will not be recognized by the service. The streamer still receives the tip, but the tip is never recognized by the system.

Other times, however, the tip is recognized by the system but the alert is still not displayed on stream.

The key methods that you'll need to look at it are:
https://github.com/pokkst/tipbitcoin.cash/blob/d84fb63491f6d553e88d691823eb967e17e07044/app/tippage.py#L39

and the other method to look at:
https://github.com/pokkst/tipbitcoin.cash/blob/d84fb63491f6d553e88d691823eb967e17e07044/app/tippage.py#L72

# verify_payment

This is called from
https://github.com/pokkst/tipbitcoin.cash/blob/d84fb63491f6d553e88d691823eb967e17e07044/app/static/js/tippagescripts.js#L109

which is called from the tip page when the user has created an invoice and is about to send to the address.

# payment_notify

This is called when the payment is verified. It sends an alert to Streamlabs via their API. Occasionally, when the payment is verified, the alert will still not show.

This is about all I know regarding the bug. I've been trying to narrow it down for weeks but it keeps coming back. Any help is appreciated.

Thank you.

**Comment by acidsploit** [comment]
Have you looked for possible race conditions?

**Comment by pokkst** [comment]
> Have you looked for possible race conditions?

I have not.

**Comment by imaginaryusername** [comment]
Will pay $100 in BCH via Gitcash to whoever can reasonably identify the problem, and then have the fixed tipbot operate at least one week without similar problems.

**Comment by CollinEnstad** [comment]
I'll also add $100 to this bounty

**Comment by pokkst** [comment]
I believe this issue is fixed. I've just pushed a commit fixing this issue.

Didn't do anything special per se, just made it so random server selection is done at a different point in the code, then passed through the verification methods.

https://github.com/pokkst/tipbitcoin.cash/commit/4f4279b5927a5231ef49bc56bdbc0efb88009ea0

Closing this for now.

**Comment by imaginaryusername** [comment]
@gitcash send $100 to @pokkst

**Comment by GitCash** [comment]
Hey **pokkst**, user **imaginaryusername** tipped you **336700 bits** in Bitcoin Cash ( ~ **$100** ).

*[Click here to claim it!](https://gitcash.io/claim/pokkst)*

You can also add the "thumbs down" reaction to **imaginaryusername**'s comment above to prevent future tips.
